"""
Cold Start AI — GTM Execution Engine
Not a strategy generator. An operating system for launching products.
"""
import os
import json
import asyncio
import io
from datetime import datetime
from fastapi import FastAPI, Request
from fastapi.responses import HTMLResponse, JSONResponse, StreamingResponse
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates
from anthropic import AsyncAnthropic

from app.agents.registry import AGENTS, AGENT_ORDER, CATEGORIES

app = FastAPI(title="Cold Start AI")
app.mount("/static", StaticFiles(directory="app/static"), name="static")
templates = Jinja2Templates(directory="app/templates")

client = None


def get_client():
    global client
    if client is None:
        client = AsyncAnthropic(api_key=os.environ.get("ANTHROPIC_API_KEY", ""))
    return client


@app.get("/", response_class=HTMLResponse)
async def landing(request: Request):
    return templates.TemplateResponse("landing.html", {
        "request": request,
        "agents": AGENTS,
        "agent_order": AGENT_ORDER,
        "categories": CATEGORIES,
    })


@app.get("/launch", response_class=HTMLResponse)
async def intake(request: Request):
    return templates.TemplateResponse("intake.html", {
        "request": request,
        "agents": AGENTS,
        "agent_order": AGENT_ORDER,
        "categories": CATEGORIES,
    })


@app.get("/dashboard", response_class=HTMLResponse)
async def dashboard(request: Request):
    return templates.TemplateResponse("dashboard.html", {
        "request": request,
        "agents": AGENTS,
        "agent_order": AGENT_ORDER,
        "categories": CATEGORIES,
    })


@app.get("/pricing", response_class=HTMLResponse)
async def pricing(request: Request):
    return templates.TemplateResponse("pricing.html", {"request": request})


@app.post("/api/generate-single")
async def generate_single(request: Request):
    body = await request.json()
    agent_id = body.get("agent_id", "")
    company_context = body.get("company_context", "")

    if agent_id not in AGENTS:
        return JSONResponse({"status": "error", "message": "Unknown agent"}, status_code=400)

    agent = AGENTS[agent_id]
    api_key = os.environ.get("ANTHROPIC_API_KEY", "")

    if not api_key:
        return JSONResponse({
            "status": "demo",
            "agent_id": agent_id,
            "name": agent["name"],
            "icon": agent["icon"],
            "deliverable": agent["deliverable"],
            "content": generate_demo_content(agent_id, agent, company_context),
        })

    try:
        message = await get_client().messages.create(
            model="claude-sonnet-4-20250514",
            max_tokens=6000,
            messages=[{
                "role": "user",
                "content": f"{agent['prompt']}\n\n---\n\nHere is the company information:\n{company_context}"
            }]
        )
        return JSONResponse({
            "status": "complete",
            "agent_id": agent_id,
            "name": agent["name"],
            "icon": agent["icon"],
            "deliverable": agent["deliverable"],
            "content": message.content[0].text,
        })
    except Exception as e:
        return JSONResponse({
            "status": "error",
            "agent_id": agent_id,
            "name": agent["name"],
            "icon": agent["icon"],
            "content": f"Error: {str(e)}",
        })


@app.post("/api/export")
async def export_results(request: Request):
    """Export all results as a single markdown document."""
    body = await request.json()
    company_name = body.get("company_name", "Company")
    results = body.get("results", {})

    doc = f"""# Cold Start AI — GTM Execution Package
## {company_name}
### Generated {datetime.now().strftime('%B %d, %Y')}

---

"""
    for agent_id in AGENT_ORDER:
        if agent_id in results and results[agent_id].get("content"):
            r = results[agent_id]
            doc += f"\n\n---\n\n# {r.get('icon', '')} {r.get('name', agent_id)}\n\n"
            doc += r["content"]
            doc += "\n"

    doc += f"""

---

*Generated by Cold Start AI — The GTM Execution Engine*
*{datetime.now().strftime('%B %d, %Y')}*
"""

    buffer = io.BytesIO(doc.encode("utf-8"))
    filename = f"coldstart-gtm-{company_name.lower().replace(' ', '-')}-{datetime.now().strftime('%Y%m%d')}.md"

    return StreamingResponse(
        buffer,
        media_type="text/markdown",
        headers={"Content-Disposition": f"attachment; filename={filename}"}
    )


@app.post("/api/export-single")
async def export_single(request: Request):
    """Export a single agent's output."""
    body = await request.json()
    agent_id = body.get("agent_id", "")
    content = body.get("content", "")
    company_name = body.get("company_name", "Company")

    agent = AGENTS.get(agent_id, {})
    name = agent.get("name", agent_id)

    doc = f"""# {agent.get('icon', '')} {name}
## {company_name}
### Generated by Cold Start AI — {datetime.now().strftime('%B %d, %Y')}

---

{content}

---

*Generated by Cold Start AI*
"""
    buffer = io.BytesIO(doc.encode("utf-8"))
    filename = f"coldstart-{agent_id}-{company_name.lower().replace(' ', '-')}.md"

    return StreamingResponse(
        buffer,
        media_type="text/markdown",
        headers={"Content-Disposition": f"attachment; filename={filename}"}
    )


def generate_demo_content(agent_id, agent, company_context):
    """Generate rich demo content that shows the format of real output."""
    company_name = "Your Company"
    for line in company_context.split("\n"):
        if line.startswith("COMPANY:"):
            company_name = line.replace("COMPANY:", "").strip() or "Your Company"
            break

    return f"""## {agent['icon']} {agent['name']} — {agent['deliverable']}

*{agent['tagline']}*

---

### This is Demo Mode

When you add your `ANTHROPIC_API_KEY`, this agent will produce a **complete {agent['deliverable']}** for **{company_name}**, including:

{agent.get('description', '')}

**Deliverable format:** {agent.get('deliverable_format', 'Document')}

---

### What You'll Get

This agent doesn't just give advice — it produces **ready-to-use assets** that you can download and deploy immediately:

- Complete document formatted for your team
- Copy-paste ready templates and scripts
- Specific numbers, targets, and benchmarks
- Actionable checklists and frameworks

---

> **To activate:** Set the `ANTHROPIC_API_KEY` environment variable and re-run your launch.

```bash
export ANTHROPIC_API_KEY=your-key-here
```
"""
